<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.14">
  <POU Name="TEST" Id="{738b160f-042e-4038-adcd-a65b7bb2eca0}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TEST
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="TEST">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>