<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.14">
  <POU Name="TEST2" Id="{9d48b9b3-5efd-469d-8dc8-c79a998fc515}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TEST2
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="TEST2">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>